"""
See COPYRIGHT.md for copyright information.
"""

from __future__ import annotations

INLINE_XBRL_REPORT_PACKAGE_EXTENSION = ".xbri"
NON_INLINE_XBRL_REPORT_PACKAGE_EXTENSION = ".xbr"
UNCONSTRAINED_REPORT_PACKAGE_EXTENSION = ".zip"

CONSTRAINED_REPORT_PACKAGE_EXTENSIONS = frozenset(
    [
        INLINE_XBRL_REPORT_PACKAGE_EXTENSION,
        NON_INLINE_XBRL_REPORT_PACKAGE_EXTENSION,
    ]
)



REPORT_PACKAGE_EXTENSIONS = frozenset(
    [
        INLINE_XBRL_REPORT_PACKAGE_EXTENSION,
        NON_INLINE_XBRL_REPORT_PACKAGE_EXTENSION,
        UNCONSTRAINED_REPORT_PACKAGE_EXTENSION,
        UNCONSTRAINED_REPORT_PACKAGE_EXTENSION.upper(),
    ]
)

REPORT_PACKAGE_FILE = "META-INF/reportPackage.json"
REPORTS_DIRECTORY = "reports"
REPORT_PACKAGE_PATHS = [REPORT_PACKAGE_FILE, f"{REPORTS_DIRECTORY}/"]
