"""
See COPYRIGHT.md for copyright information.
"""
from __future__ import annotations

from arelle.Cntlr import Cntlr
from arelle.ModelValue import qnameNsLocalName
from arelle.ValidateXbrl import ValidateXbrl
from arelle.typing import TypeGetText
from arelle.utils.validate.ValidationPlugin import ValidationPlugin
from .PluginValidationDataExtension import PluginValidationDataExtension

import regex as re

_: TypeGetText

DANISH_CURRENCY_ID = "DKK"
NAMESPACE_ARR = "http://xbrl.dcca.dk/arr"
NAMESPACE_CMN = "http://xbrl.dcca.dk/cmn"
NAMESPACE_FSA = "http://xbrl.dcca.dk/fsa"
NAMESPACE_GSD = "http://xbrl.dcca.dk/gsd"
NAMESPACE_SOB = "http://xbrl.dcca.dk/sob"
PERSONNEL_EXPENSE_THRESHOLD = 200000
ROUNDING_MARGIN = 1000
REQUIRED_STATEMENT_OF_CHANGES_IN_EQUITY_FACTS = 3
REQUIRED_DISCLOSURE_OF_EQUITY_FACTS = 2


class ValidationPluginExtension(ValidationPlugin):
    def newPluginData(self, cntlr: Cntlr, validateXbrl: ValidateXbrl | None) -> PluginValidationDataExtension:
        return PluginValidationDataExtension(
            self.name,
            accountingPolicyConceptQns=frozenset([
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionMethodsOfRecognitionAndMeasurementBasisForCashFlowsStatement"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfAccountingPoliciesRelatedToDerivativeFinancialInstruments"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfAnyFailureOfApplyingEliminationBetweenConsolidatedEnterprises"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfChangeInInventoriesOfFinishedGoodsWorkInProgressAndGoodsForResale"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfChangesInCompositionOfEntityActivities"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfEffectOfChangeInAccountingEstimatesOnAssetsLiabilitiesEquityFinancialPositionAndResults"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfEffectOfChangeInRecognitionAndMeasurementBasisOfAssetsAndLiabilitiesAsResultOfErrors"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfEffectOfDerogationFromProvisionsOfDanishFinancialStatementsActOnAssetsLiabilitiesEquityFinancialPositionAndResults"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfGeneralMattersRelatedToRecognitionMeasurementAndChangesInAccountingPolicies"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfImpairmentOfFinancialAssets"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfIncomeFromOtherInvestmentsAndReceivablesThatAreFixedAssets"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfKeyFiguresAndFinancialRatios"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfAmortisationOfNoncurrentAssets"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfAssetsMeantForSale"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfCurrentTaxReceivablesAndLiabilities"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfDividends"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfForeignCurrencies"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfHedgingRecognisedExpectedToReceiveAndAssumedAssetsAndLiabilities"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfImpairmentLossesAndDepreciation"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfIncomeExceedCostAndCostExceedsIncomeForTheFinancialYear"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfInvestments"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfInvestmentsAsCurrentAssets"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfLeases"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfLiquidationAccount"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfPrepayments"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisForDistributions"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisForInvestmentsInJointVentures"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisForInvestmentsInSubsidiariesAndAssociates"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisIncludingBasesUsedForRevaluationsDepreciationAmortisationEstimatedResidualValueUsefulLifeWritedownsUpwardAndDownwardAdjustments"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfAdministrativeExpenses"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfAssetsAndLiabilities"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfCashAndCashEquivalents"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfContractWorkInProgress"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfCostOfProduction"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfCostOfSales"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfDeferredIncomeAssets"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfDeferredIncomeLiabilities"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfDistributionCosts"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfEmployeeBenefitExpense"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfEquity"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfExpensesFromInvestmentsInGroupEnterprisesAndAssociates"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfExternalExpenses"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfFinanceExpenses"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfFinanceIncome"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfFinanceIncomeAndExpenses"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfGainsLossesFromCurrentValueAdjustmentsOfBiologicalAssets"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfGainsLossesFromCurrentValueAdjustmentsOfInvestmentProperty"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfGainsLossesFromCurrentValueAdjustmentsOfOtherInvestmentAssets"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfGrossProfitLoss"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfIncomeAndExpensesFromInvestmentsInGroupEnterprisesAndAssociates"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfIncomeAndExpensesFromInvestmentsInJointVentures"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfIncomeFromInvestmentsInGroupEnterprisesAndAssociates"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfIncomeStatementItems"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfIndirectCostsOfProductionRecognisedUnderAssets"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfIntangibleAssets"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfInventories"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfInvestmentProperty"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfInvestments"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfLeaseholdImprovements"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfLiabilitiesOtherThanProvisions"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfOtherInvestmentAssets"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfOtherOperatingExpenses"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfOtherOperatingIncome"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfOtherOperatingIncomeAndExpenses"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfOtherProvisions"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfPropertyCosts"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfPropertyPlantAndEquipment"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfProvisions"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfReceivables"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfResearchAndDevelopmentExpendituresRecognisedAsExpenses"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfRevenue"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfSpecialItems"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfTaxExpenses"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfTaxPayablesAndDeferredTax"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisUsedAtEstablishment"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfRecognitionAndMeasurementBasisUsedInBusinessCombinations"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfStatingKeyFiguresAndFinancialRatiosIncludedInManagementReview"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfMethodsOfTranslationOfForeignCurrencies"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfOtherKeyFiguresAndFinancialRatios"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfOtherTaxExpenses"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfOwnWorkCapitalised"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfPublicGrants"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfRawMaterialsAndConsumablesUsed"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfRecognitionAndMeasurementBasisForDiscontinuedOperationsBalanceSheet"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfRemainingPositiveOrNegativeBalancesRelatedToAcquisitionAndUnitingOfInterestsAndMethodsUsedInConnectionWithTheirCalculation"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfWritedownsOfCurrentAssetsThatExceedNormalWritedowns"),
                qnameNsLocalName(NAMESPACE_FSA, "DisclosureOfAccountingPolicies"),
                qnameNsLocalName(NAMESPACE_FSA, "DisclosureOfTrueAndFairViewAndGoingConcern"),
                qnameNsLocalName(NAMESPACE_FSA, "ExplanationOfAmortizationPeriodForGoodwill"),
                qnameNsLocalName(NAMESPACE_FSA, "ExplanationOfAssumptionsOnWhichChosenCalculationMethodHasBeenBasedForFinancialAssetsAndLiabilitiesMeasuredAtNetPresentValueOrAmortisedCost"),
                qnameNsLocalName(NAMESPACE_FSA, "ExplanationOfAssumptionsOnWhichChosenCalculationMethodHasBeenBasedForInvestmentsAndBiologicalAssetsMeasuredAtFairValue"),
                qnameNsLocalName(NAMESPACE_FSA, "ExplanationOfBasisOnWhichEquityInvestmentsInSubsidiariesAndAssociatesHaveBeenRecognisedAtCost"),
                qnameNsLocalName(NAMESPACE_FSA, "ExplanationOfChangeInAccountingEstimates"),
                qnameNsLocalName(NAMESPACE_FSA, "ExplanationOfChangeInRecognitionAndMeasurementBasisOfAssetsAndLiabilitiesAsResultOfErrors"),
                qnameNsLocalName(NAMESPACE_FSA, "ExplanationOfDerogationFromProvisionsOfDanishFinancialStatementsActOnAssetsLiabilitiesEquityFinancialPositionAndResults"),
                qnameNsLocalName(NAMESPACE_FSA, "ExplanationOfDifferenceInBalanceSheetDatesBetweenParentAndConsolidatedSubsidiariesAndDescriptionOfImportantEventsOccurringAtThatTime"),
                qnameNsLocalName(NAMESPACE_FSA, "ExplanationOfDifferenceInMethodsOfRecognitionAndMeasurementBasisBetweenParentAndConsolidatedGroupEnterprise"),
                qnameNsLocalName(NAMESPACE_FSA, "ExplanationOfEntitysDefinitionOfCashAndCashEquivalents"),
                qnameNsLocalName(NAMESPACE_FSA, "ExplanationOfGroundsOfNoncomparabilityOrRestatement"),
                qnameNsLocalName(NAMESPACE_FSA, "ExplanationOfNotDisclosingInformationOnAGroupEntity"),
                qnameNsLocalName(NAMESPACE_FSA, "ExplanationOfOtherMethodsOfRecognitionAndMeasurementBasisForAssetsInPreviousPeriod"),
                qnameNsLocalName(NAMESPACE_FSA, "ExplanationOfWhetherInterestIsIncludedInCost"),
                qnameNsLocalName(NAMESPACE_FSA, "InformationOnChangesAndEffectsOfChangesOnRecognitionAndMeasurementBasisResultingFromChangesInAccountingEstimatesOrErrors"),
                qnameNsLocalName(NAMESPACE_FSA, "InformationOnConsolidatedResultsAndEquityIfSubsidiaryHasNotBeenPreviouslyIncludedInConsolidatedFinancialStatementsAndParentHoldsInvestmentsInSubsidiarySolelyWithViewToItsSubsequentTransfer"),
                qnameNsLocalName(NAMESPACE_FSA, "InformationOnConsolidations"),
                qnameNsLocalName(NAMESPACE_FSA, "InformationOnHedging"),
                qnameNsLocalName(NAMESPACE_FSA, "InformationOnIncentivePrograms"),
                qnameNsLocalName(NAMESPACE_FSA, "InformationOnIntragroupTransactions"),
                qnameNsLocalName(NAMESPACE_FSA, "InformationOnLeasingContracts"),
                qnameNsLocalName(NAMESPACE_FSA, "InformationOnMinorityInterests"),
                qnameNsLocalName(NAMESPACE_FSA, "InformationOnNoncomparabilityOrRestatement"),
                qnameNsLocalName(NAMESPACE_FSA, "InformationOnOmissionOfConsolidatedFinancialStatement"),
                qnameNsLocalName(NAMESPACE_FSA, "InformationOnReportingClassOfEntity"),
                qnameNsLocalName(NAMESPACE_FSA, "InformationOnSegments"),
                qnameNsLocalName(NAMESPACE_FSA, "InformationOnSignificantUncertainties"),
                qnameNsLocalName(NAMESPACE_FSA, "InformationOnSpecificPrerequisitesRegardingDevelopmentProjectsAndTaxAssets"),
                qnameNsLocalName(NAMESPACE_FSA, "InformationOnSubsequentEvents"),
                qnameNsLocalName(NAMESPACE_FSA, "InformationOnSubsidiariesHavingPresentedTheAnnualReportEtcWithReferenceToTheDanishFinancialStatementsAct78aConcerningTheExceptionForReportingClassCMediumsizeSubsidiariesWhichChoosesToPresentTheAnnualReportEtcAccordingToReportingClassB"),
                qnameNsLocalName(NAMESPACE_FSA, "InformationOnThePrincipalModificationsAsResultOfTheLiquidation"),
                qnameNsLocalName(NAMESPACE_FSA, "InformationOnTimingDifferencesInCustomerPaymentsEspeciallyForUtilities"),
                qnameNsLocalName(NAMESPACE_FSA, "InformationOnTreatmentOfAdditionalPaymentsFromAndRepaymentsToRelatedParties"),
                qnameNsLocalName(NAMESPACE_FSA, "InformationOnTrueAndFairViewIfProvisionsOfDanishFinancialStatementsActAreNotSufficient"),
                qnameNsLocalName(NAMESPACE_FSA, "InformationOnUncertaintiesRelatingToGoingConcern"),
                qnameNsLocalName(NAMESPACE_FSA, "SubsidiariesHasPresentedTheAnnualReportEtc.WithReferenceToTheDanishFinancialStatementsAct78aConcerningTheExceptionForReportingClassCMediumsizeSubsidiariesWhichChoosesToPresentTheAnnualReportEtcAccordingToReportingClassB"),
            ]),
            addressOfSubmittingEnterprisePostcodeAndTownQn=qnameNsLocalName(NAMESPACE_GSD, "AddressOfSubmittingEnterprisePostcodeAndTown"),
            addressOfSubmittingEnterpriseStreetAndNumberQn=qnameNsLocalName(NAMESPACE_GSD, "AddressOfSubmittingEnterpriseStreetAndNumber"),
            allReportingPeriodsMemberQn=qnameNsLocalName(NAMESPACE_GSD, "AllReportingPeriodsMember"),
            annualReportTypes=frozenset([
                "Årsrapport",
                "årsrapport",
                "Annual report",
                "Likvidationsregnskab",
                "likvidationsregnskab",
                "Liquidation accounts",
            ]),
            assetsQn=qnameNsLocalName(NAMESPACE_FSA, "Assets"),
            auditedAssuranceReportsDanish="Andre erklæringer med sikkerhed",
            auditedAssuranceReportsEnglish="The independent auditor's reports (Other assurance Reports)",
            auditedExtendedReviewDanish="Erklæring om udvidet gennemgang",
            auditedExtendedReviewEnglish="Auditor's report on extended review",
            auditedFinancialStatementsDanish="Revisionspåtegning",
            auditedFinancialStatementsEnglish="Auditor's report on audited financial statements",
            auditedNonAssuranceReportsDanish="Andre erklæringer uden sikkerhed",
            auditedNonAssuranceReportsEnglish="Auditor's reports (Other non-assurance reports)",
            averageNumberOfEmployeesQn=qnameNsLocalName(NAMESPACE_FSA, "AverageNumberOfEmployees"),
            balanceSheetQnLessThanOrEqualToAssets=frozenset([
                qnameNsLocalName(NAMESPACE_FSA, "NoncurrentAssets"),
                qnameNsLocalName(NAMESPACE_FSA, "IntangibleAssets"),
                qnameNsLocalName(NAMESPACE_FSA, "CompletedDevelopmentProjects"),
                qnameNsLocalName(NAMESPACE_FSA, "ConcessionsOriginatingFromDevelopmentProjects"),
                qnameNsLocalName(NAMESPACE_FSA, "PatentsOriginatingFromDevelopmentProjects"),
                qnameNsLocalName(NAMESPACE_FSA, "TrademarksOriginatingFromDevelopmentProjects"),
                qnameNsLocalName(NAMESPACE_FSA, "OtherSimilarRightsOriginatingFromDevelopmentProjects"),
                qnameNsLocalName(NAMESPACE_FSA, "AcquiredIntangibleAssets"),
                qnameNsLocalName(NAMESPACE_FSA, "AcquiredConcessions"),
                qnameNsLocalName(NAMESPACE_FSA, "AcquiredPatents"),
                qnameNsLocalName(NAMESPACE_FSA, "AcquiredLicences"),
                qnameNsLocalName(NAMESPACE_FSA, "AcquiredTrademarks"),
                qnameNsLocalName(NAMESPACE_FSA, "AcquiredOtherSimilarRights"),
                qnameNsLocalName(NAMESPACE_FSA, "Goodwill"),
                qnameNsLocalName(NAMESPACE_FSA, "DevelopmentProjectsInProgressAndPrepaymentsForIntangibleAssets"),
                qnameNsLocalName(NAMESPACE_FSA, "DevelopmentProjectsInProgress"),
                qnameNsLocalName(NAMESPACE_FSA, "PrepaymentsForIntangibleAssets"),
                qnameNsLocalName(NAMESPACE_FSA, "PropertyPlantAndEquipment"),
                qnameNsLocalName(NAMESPACE_FSA, "LandAndBuildings"),
                qnameNsLocalName(NAMESPACE_FSA, "Land"),
                qnameNsLocalName(NAMESPACE_FSA, "Buildings"),
                qnameNsLocalName(NAMESPACE_FSA, "InvestmentProperty"),
                qnameNsLocalName(NAMESPACE_FSA, "OtherInvestmentAssets"),
                qnameNsLocalName(NAMESPACE_FSA, "PlantAndMachinery"),
                qnameNsLocalName(NAMESPACE_FSA, "FixturesFittingsToolsAndEquipment"),
                qnameNsLocalName(NAMESPACE_FSA, "BiologicalAssets"),
                qnameNsLocalName(NAMESPACE_FSA, "LeaseholdImprovements"),
                qnameNsLocalName(NAMESPACE_FSA, "Ships"),
                qnameNsLocalName(NAMESPACE_FSA, "Planes"),
                qnameNsLocalName(NAMESPACE_FSA, "RightofuseAssets"),
                qnameNsLocalName(NAMESPACE_FSA, "PropertyPlantAndEquipmentInProgressAndPrepaymentsForPropertyPlantAndEquipment"),
                qnameNsLocalName(NAMESPACE_FSA, "PropertyPlantAndEquipmentInProgress"),
                qnameNsLocalName(NAMESPACE_FSA, "PrepaymentsForPropertyPlantAndEquipment"),
                qnameNsLocalName(NAMESPACE_FSA, "LongtermInvestmentsAndReceivables"),
                qnameNsLocalName(NAMESPACE_FSA, "LongtermInvestmentsInGroupEnterprises"),
                qnameNsLocalName(NAMESPACE_FSA, "LongtermInvestmentsInAssociates"),
                qnameNsLocalName(NAMESPACE_FSA, "LongtermParticipatingInterests"),
                qnameNsLocalName(NAMESPACE_FSA, "LongtermInvestmentsInJointVentures"),
                qnameNsLocalName(NAMESPACE_FSA, "LongtermReceivablesFromGroupEnterprises"),
                qnameNsLocalName(NAMESPACE_FSA, "LongtermReceivablesFromAssociates"),
                qnameNsLocalName(NAMESPACE_FSA, "LongtermReceivablesFromParticipatingInterests"),
                qnameNsLocalName(NAMESPACE_FSA, "LongtermReceivablesFromJointVentures"),
                qnameNsLocalName(NAMESPACE_FSA, "OtherLongtermInvestments"),
                qnameNsLocalName(NAMESPACE_FSA, "OtherLongtermReceivables"),
                qnameNsLocalName(NAMESPACE_FSA, "LongtermReceivablesFromOwnersAndManagement"),
                qnameNsLocalName(NAMESPACE_FSA, "NoncurrentDeferredTaxAssets"),
                qnameNsLocalName(NAMESPACE_FSA, "DepositsLongtermInvestmentsAndReceivables"),
                qnameNsLocalName(NAMESPACE_FSA, "CostExceedsIncomeForTheFinancialYearLongtermReceivables"),
                qnameNsLocalName(NAMESPACE_FSA, "ContributedCapitalInArrearsLongTerm"),
                qnameNsLocalName(NAMESPACE_FSA, "NoncurrentContractAssets"),
                qnameNsLocalName(NAMESPACE_FSA, "CurrentAssets"),
                qnameNsLocalName(NAMESPACE_FSA, "Inventories"),
                qnameNsLocalName(NAMESPACE_FSA, "RawMaterialsAndConsumables"),
                qnameNsLocalName(NAMESPACE_FSA, "WorkInProgress"),
                qnameNsLocalName(NAMESPACE_FSA, "ManufacturedGoodsAndGoodsForResale"),
                qnameNsLocalName(NAMESPACE_FSA, "PrepaymentsForGoods"),
                qnameNsLocalName(NAMESPACE_FSA, "Livestock"),
                qnameNsLocalName(NAMESPACE_FSA, "PropertyHeldForSaleInTheOrdinaryCourseOfBusiness"),
                qnameNsLocalName(NAMESPACE_FSA, "AssetsHeldForSaleInventories"),
                qnameNsLocalName(NAMESPACE_FSA, "ShorttermReceivables"),
                qnameNsLocalName(NAMESPACE_FSA, "ShorttermTradeReceivables"),
                qnameNsLocalName(NAMESPACE_FSA, "ContractWorkInProgress"),
                qnameNsLocalName(NAMESPACE_FSA, "ShorttermReceivablesFromGroupEnterprises"),
                qnameNsLocalName(NAMESPACE_FSA, "ShorttermReceivablesFromAssociates"),
                qnameNsLocalName(NAMESPACE_FSA, "ShorttermReceivablesFromJointVentures"),
                qnameNsLocalName(NAMESPACE_FSA, "ShorttermReceivablesFromParticipatingInterests"),
                qnameNsLocalName(NAMESPACE_FSA, "ShorttermReceivablesDividendsFromGroupEnterprises"),
                qnameNsLocalName(NAMESPACE_FSA, "ShorttermReceivablesDividendsFromAssociates"),
                qnameNsLocalName(NAMESPACE_FSA, "ShorttermReceivablesDividendsFromJointVentures"),
                qnameNsLocalName(NAMESPACE_FSA, "ShorttermReceivablesDividendsFromParticipatingInterests"),
                qnameNsLocalName(NAMESPACE_FSA, "CurrentDeferredTaxAssets"),
                qnameNsLocalName(NAMESPACE_FSA, "ShorttermTaxReceivables"),
                qnameNsLocalName(NAMESPACE_FSA, "ShorttermTaxReceivablesFromGroupEnterprises"),
                qnameNsLocalName(NAMESPACE_FSA, "VatAndDutiesReceivables"),
                qnameNsLocalName(NAMESPACE_FSA, "OtherShorttermReceivables"),
                qnameNsLocalName(NAMESPACE_FSA, "ContributedCapitalInArrears"),
                qnameNsLocalName(NAMESPACE_FSA, "ShorttermReceivablesFromOwnersAndManagement"),
                qnameNsLocalName(NAMESPACE_FSA, "DeferredIncomeAssets"),
                qnameNsLocalName(NAMESPACE_FSA, "CostExceedsIncomeForTheFinancialYearShorttermReceivables"),
                qnameNsLocalName(NAMESPACE_FSA, "TimingDifferencesShorttermReceivablesEspeciallyUtilities"),
                qnameNsLocalName(NAMESPACE_FSA, "CurrentContractAssets"),
                qnameNsLocalName(NAMESPACE_FSA, "DerivativeFinancialInstrumentsShorttermAssets"),
                qnameNsLocalName(NAMESPACE_FSA, "ShorttermInvestments"),
                qnameNsLocalName(NAMESPACE_FSA, "ShorttermInvestmentsInGroupEnterprises"),
                qnameNsLocalName(NAMESPACE_FSA, "OtherShorttermInvestments"),
                qnameNsLocalName(NAMESPACE_FSA, "CashAndCashEquivalents"),
                qnameNsLocalName(NAMESPACE_FSA, "AssetsMeantForSale"),
            ]),
            basisForAdverseOpinionDanish="Grundlag for afkræftende konklusion",
            basisForAdverseOpinionEnglish="Basis for Adverse Opinion",
            basisForDisclaimerOpinionDanish="Grundlag for manglende konklusion",
            basisForDisclaimerOpinionEnglish="Basis for Disclaimer of Opinion",
            basisForQualifiedOpinionDanish="Grundlag for konklusion med forbehold",
            basisForQualifiedOpinionEnglish="Basis for Qualified Opinion",
            classOfReportingEntityQn=qnameNsLocalName(NAMESPACE_FSA, "ClassOfReportingEntity"),
            cClassOfReportingEntityEnums = frozenset([
                "SelectedElementsFromReportingClassD",
                "Reporting class C, medium-size enterprise",
                "Regnskabsklasse C, stor virksomhed",
                "Reporting class C, large enterprise"]),
            dClassOfReportingEntityEnums = frozenset([
                "Regnskabsklasse D",
                "Reporting class D"
            ]),
            consolidatedMemberQn=qnameNsLocalName(NAMESPACE_CMN, "ConsolidatedMember"),
            consolidatedSoloDimensionQn=qnameNsLocalName(NAMESPACE_CMN, "ConsolidatedSoloDimension"),
            cpr_regex=re.compile(r"^([0-2][0-9]|3[0-1])(0[1-9]|1[0-2])[0-9]{2}-[0-9]{4}"),
            dateOfApprovalOfAnnualReportQn=qnameNsLocalName(NAMESPACE_SOB, "DateOfApprovalOfAnnualReport"),
            dateOfExtraordinaryDividendDistributedAfterEndOfReportingPeriod=qnameNsLocalName(NAMESPACE_FSA, "DateOfExtraordinaryDividendDistributedAfterEndOfReportingPeriod"),
            dateOfGeneralMeetingQn=qnameNsLocalName(NAMESPACE_GSD, "DateOfGeneralMeeting"),
            declarationObligationQns=frozenset([
                qnameNsLocalName(NAMESPACE_ARR, "ReportingResponsibilitiesAccordingToTheDanishExecutiveOrderOnApprovedAuditorsReportsEspeciallyTheCriminalCodeAndFiscalTaxAndSubsidyLegislationAudit"),
                qnameNsLocalName(NAMESPACE_ARR, "ReportingResponsibilitiesAccordingToTheDanishExecutiveOrderOnApprovedAuditorsReportsEspeciallyTheCompaniesActOrEquivalentLegislationThatTheCompanyIsSubjectToAudit"),
                qnameNsLocalName(NAMESPACE_ARR, "ReportingResponsibilitiesAccordingToTheDanishExecutiveOrderOnApprovedAuditorsReportsEspeciallyLegislationOnFinancialReportingIncludingAccountingAndStorageOfAccountingRecordsAudit"),
                qnameNsLocalName(NAMESPACE_ARR, "ReportingResponsibilitiesAccordingToTheDanishExecutiveOrderOnApprovedAuditorsReportsEspeciallyOtherMattersAudit"),
                ]),
            descriptionOfQualificationsOfAssuranceEngagementPerformedQn=qnameNsLocalName(NAMESPACE_ARR, "DescriptionOfQualificationsOfAssuranceEngagementPerformed"),
            descriptionOfQualificationsOfAuditedFinancialStatementsQn=qnameNsLocalName(NAMESPACE_ARR, "DescriptionOfQualificationsOfAuditedFinancialStatements"),
            descriptionOfQualificationsOfFinancialStatementsExtendedReviewQn=qnameNsLocalName(NAMESPACE_ARR, "DescriptionOfQualificationsOfFinancialStatementsExtendedReview"),
            descriptionsOfQualificationsOfReviewedFinancialStatementsQn=qnameNsLocalName(NAMESPACE_ARR, "DescriptionsOfQualificationsOfReviewedFinancialStatements"),
            disclosureOfEquityQns=frozenset([
                qnameNsLocalName(NAMESPACE_FSA, "InformationOnClassesOfIssuedShares"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfClassOfIssuedShares"),
                qnameNsLocalName(NAMESPACE_FSA, "NumberOfIssuedShares"),
                qnameNsLocalName(NAMESPACE_FSA, "NominelValuePerUnitShare"),
                qnameNsLocalName(NAMESPACE_FSA, "AccountingParValuePerUnitShare"),
                qnameNsLocalName(NAMESPACE_FSA, "NominalValueOfIssuedShares"),
                qnameNsLocalName(NAMESPACE_FSA, "InformationOnExpensesIncurredInFormationOfEntityOrIncreaseInShareCapital"),
                qnameNsLocalName(NAMESPACE_FSA, "ExpensesIncurredInFormationOfEntityOrIncreaseInShareCapital"),
                qnameNsLocalName(NAMESPACE_FSA, "RetrospectiveInformationOnContributedCapital"),
                qnameNsLocalName(NAMESPACE_FSA, "IncreaseDecreaseOfCapital"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfTreasurySharesHold"),
                qnameNsLocalName(NAMESPACE_FSA, "NumberOfTreasurySharesHold"),
                qnameNsLocalName(NAMESPACE_FSA, "NominalValueOfTreasurySharesHold"),
                qnameNsLocalName(NAMESPACE_FSA, "AccountingParValueOfTreasurySharesHold"),
                qnameNsLocalName(NAMESPACE_FSA, "PercentageOfContributedCapitalOfTreasurySharesHold"),
                qnameNsLocalName(NAMESPACE_FSA, "InformationOnTreasurySharesAcquired"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfTreasurySharesAcquired"),
                qnameNsLocalName(NAMESPACE_FSA, "NumberOfTreasurySharesAcquired"),
                qnameNsLocalName(NAMESPACE_FSA, "NominalValueOfTreasurySharesAcquired"),
                qnameNsLocalName(NAMESPACE_FSA, "AccountingParValueOfTreasurySharesAcquired"),
                qnameNsLocalName(NAMESPACE_FSA, "PercentageOfContributedCapitalOfTreasurySharesAcquired"),
                qnameNsLocalName(NAMESPACE_FSA, "PurchasePriceOfTreasurySharesAcquired"),
                qnameNsLocalName(NAMESPACE_FSA, "ExplanationOfReasonForAcquisitionOfTreasuryShares"),
                qnameNsLocalName(NAMESPACE_FSA, "InformationOnTreasurySharesSold"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfTreasurySharesSold"),
                qnameNsLocalName(NAMESPACE_FSA, "NumberOfTreasurySharesSold"),
                qnameNsLocalName(NAMESPACE_FSA, "NominalValueOfTreasurySharesSold"),
                qnameNsLocalName(NAMESPACE_FSA, "PercentageOfContributedCapitalOfTreasurySharesSold"),
                qnameNsLocalName(NAMESPACE_FSA, "SalesPriceOfTreasurySharesSold"),
                qnameNsLocalName(NAMESPACE_FSA, "InformationOnTreasurySharesAcquiredAsSecurity"),
                qnameNsLocalName(NAMESPACE_FSA, "DescriptionOfTreasurySharesAcquiredAsSecurity"),
                qnameNsLocalName(NAMESPACE_FSA, "NumberOfTreasurySharesAcquiredAsSecurity"),
                qnameNsLocalName(NAMESPACE_FSA, "NominalValueOfTreasurySharesAcquiredAsSecurity"),
                qnameNsLocalName(NAMESPACE_FSA, "AccountingParValueOfTreasurySharesAcquiredAsSecurity"),
                qnameNsLocalName(NAMESPACE_FSA, "PercentageOfContributedCapitalOfTreasurySharesAcquiredAsSecurity"),
                qnameNsLocalName(NAMESPACE_FSA, "PurchasePriceOfTreasurySharesAcquiredAsSecurity"),
                qnameNsLocalName(NAMESPACE_FSA, "ExplanationOfReasonForAcquisitionOfTreasurySharesAsSecurity"),
                qnameNsLocalName(NAMESPACE_FSA, "ExplanationOfChangeInMinorityInterestsProportionateShareOfSubsidiariesEquity"),
                qnameNsLocalName(NAMESPACE_FSA, "DisclosureOfDistributions"),
                qnameNsLocalName(NAMESPACE_FSA, "Distributions"),
                qnameNsLocalName(NAMESPACE_FSA, "DisclosureOfHedgeFund"),
                qnameNsLocalName(NAMESPACE_FSA, "HedgeFund"),
                qnameNsLocalName(NAMESPACE_FSA, "DisclosureOfReserveFund"),
                qnameNsLocalName(NAMESPACE_FSA, "ReserveFund"),
                qnameNsLocalName(NAMESPACE_FSA, "DisclosureOfReservesAvailable"),
                qnameNsLocalName(NAMESPACE_FSA, "TransferredToFromReservesAvailable"),
                qnameNsLocalName(NAMESPACE_FSA, "DisclosureOfLiquidationAccount"),
                qnameNsLocalName(NAMESPACE_FSA, "LiquidationAccount"),
                qnameNsLocalName(NAMESPACE_FSA, "InformationOnReserveForEntrepreneurialCompany"),
                qnameNsLocalName(NAMESPACE_FSA, "ReserveForEntrepreneurialCompany"),
                qnameNsLocalName(NAMESPACE_FSA, "InformationOnChangesAsResultOfApplicationOfUnitingOfInterestsMethod"),
                qnameNsLocalName(NAMESPACE_FSA, "IncreaseDecreaseOfReservesThroughApplicationOfUnitingOfInterestsMethodEquity"),
                qnameNsLocalName(NAMESPACE_FSA, "DisclosureOfRevaluationReserve"),
                qnameNsLocalName(NAMESPACE_FSA, "RevaluationReserve"),
                qnameNsLocalName(NAMESPACE_FSA, "AdditionsToRevaluationReserveInReportingPeriod"),
                qnameNsLocalName(NAMESPACE_FSA, "ReversalsOfPriorYearsRevaluationsOfRevaluationReserve"),
                qnameNsLocalName(NAMESPACE_FSA, "AmortisationOfRevaluationReserveInReportingPeriod"),
                qnameNsLocalName(NAMESPACE_FSA, "DisposalsOfRevaluationReserveInReportingPeriod"),
                qnameNsLocalName(NAMESPACE_FSA, "RecognitionAndMeasurementOfTheTaxEffectOfTheMovementsInTheRevaluationReserve"),
                qnameNsLocalName(NAMESPACE_FSA, "CurrentValueReserve"),
                qnameNsLocalName(NAMESPACE_FSA, "AdjustmentsOfCurrentValueReserveGainsLoss"),
                qnameNsLocalName(NAMESPACE_FSA, "CurrentValueReserveRealized"),
                qnameNsLocalName(NAMESPACE_FSA, "CurrentValueReserveReversed"),
            ]),
                distributionOfResultsQns=frozenset([
                qnameNsLocalName(NAMESPACE_FSA, "DistributionsResultDistribution"),
                qnameNsLocalName(NAMESPACE_FSA, "ExtraordinaryDistributions"),
                qnameNsLocalName(NAMESPACE_FSA, "ProposedDividendRecognisedInEquity"),
                qnameNsLocalName(NAMESPACE_FSA, "ProposedExtraordinaryDividendRecognisedInEquity"),
                qnameNsLocalName(NAMESPACE_FSA, "ProposedExtraordinaryDividendRecognisedInLiabilities"),
                qnameNsLocalName(NAMESPACE_FSA, "TransferredFromToHedgeFund"),
                qnameNsLocalName(NAMESPACE_FSA, "TransferredFromToReserveFund"),
                qnameNsLocalName(NAMESPACE_FSA, "TransferredFromToReservesAvailable"),
                qnameNsLocalName(NAMESPACE_FSA, "TransferredToFromEquityAttributableToParent"),
                qnameNsLocalName(NAMESPACE_FSA, "TransferredToFromMinorityInterests"),
                qnameNsLocalName(NAMESPACE_FSA, "TransferredToFromOtherStatutoryReserves"),
                qnameNsLocalName(NAMESPACE_FSA, "TransferredToFromReserveAccordingToArticlesOfAssociation"),
                qnameNsLocalName(NAMESPACE_FSA, "TransferredToFromReserveForNetRevaluationAccordingToEquityMethod"),
                qnameNsLocalName(NAMESPACE_FSA, "TransferredToFromReserveForNetRevaluationOfInvestmentAssets"),
                qnameNsLocalName(NAMESPACE_FSA, "TransferredToFromRestOfOtherReserves"),
                qnameNsLocalName(NAMESPACE_FSA, "TransferredToFromRetainedEarnings"),
                qnameNsLocalName(NAMESPACE_FSA, "TransferredToReserveForCurrentValueAdjustmentsOfCurrencyGains"),
                qnameNsLocalName(NAMESPACE_FSA, "TransferredToReserveForCurrentValueOfHedging"),
                qnameNsLocalName(NAMESPACE_FSA, "TransferredToReserveForDevelopmentExpenditure"),
                qnameNsLocalName(NAMESPACE_FSA, "TransferredToReserveForEntrepreneurialCompany"),
            ]),
            endDateForUseOfDigitalNonregisteredBookkeepingSystemQn=qnameNsLocalName(NAMESPACE_GSD, "EndDateForUseOfDigitalNonregisteredBookkeepingSystem"),
            endDateForUseOfDigitalStandardBookkeepingSystemQn=qnameNsLocalName(NAMESPACE_GSD, "EndDateForUseOfDigitalStandardBookkeepingSystem"),
            employeeBenefitsExpenseQn=qnameNsLocalName(NAMESPACE_FSA, "EmployeeBenefitsExpense"),
            equityQn=qnameNsLocalName(NAMESPACE_FSA, "Equity"),
            extraordinaryCostsQn=qnameNsLocalName(NAMESPACE_FSA, "ExtraordinaryCosts"),
            extraordinaryIncomeQn=qnameNsLocalName(NAMESPACE_FSA, "ExtraordinaryIncome"),
            extraordinaryResultBeforeTaxQn=qnameNsLocalName(NAMESPACE_FSA, "ExtraordinaryResultBeforeTax"),
            fr37RestrictedText="has not given rise to reservations",
            forbiddenTypeOfSubmittedReportEnumerations=frozenset([
                "Selskabsselvangivelse",
                "Erklæring om undtagelse fra aflæggelse årsrapport",
                "ESG-rapport",
                "ESG report",
                ]),
            hasNotGivenRiseToReservationsText=frozenset([
                "har ikke givet anledning til forbehold",
                "has not given rise to reservations",
            ]),
            identificationNumberCvrOfAuditFirmQn=qnameNsLocalName(NAMESPACE_CMN, "IdentificationNumberCvrOfAuditFirm"),
            identificationNumberCvrOfReportingEntityQn=qnameNsLocalName(NAMESPACE_GSD, "IdentificationNumberCvrOfReportingEntity"),
            independentAuditorsReportDanish="Den uafhængige revisors erklæring",
            independentAuditorsReportEnglish="Independent Auditor’s Report",
            independentAuditorsReportReviewDanish="Den uafhængige revisors erklæringer (review)",
            independentAuditorsReportReviewEnglish="The independent auditor’s reports (Review)",
            independentPractitionersExtendedReviewReportDanish="Den uafhængige revisors erklæring om udvidet gennemgang",
            independentPractitionersExtendedReviewReportEnglish="Independent Practitioner’s Extended Review Report",
            independentPractitionersReviewReportDanish="Den uafhængige revisors reviewerklæring",
            independentPractitionersReviewReportEnglish="Independent Practitioner’s Review Report",
            informationOnTypeOfSubmittedReportQn=qnameNsLocalName(NAMESPACE_GSD, "InformationOnTypeOfSubmittedReport"),
            legalEntityIdentifierOfReportingEntityQn=qnameNsLocalName(NAMESPACE_GSD, "LegalEntityIdentifierOfReportingEntity"),
            liabilitiesQn=qnameNsLocalName(NAMESPACE_FSA, "LiabilitiesAndEquity"),
            liabilitiesAndEquityQn=qnameNsLocalName(NAMESPACE_FSA, "LiabilitiesAndEquity"),
            liabilitiesOtherThanProvisionsQn=qnameNsLocalName(NAMESPACE_FSA, "LiabilitiesOtherThanProvisions"),
            longtermLiabilitiesOtherThanProvisionsQn=qnameNsLocalName(NAMESPACE_FSA, "LongtermLiabilitiesOtherThanProvisions"),
            managementEndorsementQns=frozenset([
                qnameNsLocalName(NAMESPACE_SOB, "StatementByExecutiveAndSupervisoryBoards"),
                qnameNsLocalName(NAMESPACE_SOB, "TheReportingEntityAppliesTheExceptionConcerningOptingOutOfTheStatementByManagementEtc"),
                qnameNsLocalName(NAMESPACE_SOB, "IdentificationOfApprovedAnnualReport"),
                qnameNsLocalName(NAMESPACE_SOB, "ConfirmationThatAnnualReportIsPresentedInAccordanceWithRequirementsProvidedForByLegislationAnyStandardsAndRequirementsProvidedByArticlesOfAssociationOrByAgreement"),
                qnameNsLocalName(NAMESPACE_SOB, "ConfirmationThatFinancialStatementGivesTrueAndFairViewOfAssetsLiabilitiesEquityFinancialPositionAndResults"),
                qnameNsLocalName(NAMESPACE_SOB, "ConfirmationThatSupplementaryReportsGiveTrueAndFairViewInAccordanceWithGenerallyAcceptedGuidelinesForSuchReports"),
                qnameNsLocalName(NAMESPACE_SOB, "ManagementsStatementAboutManagementsReview"),
                qnameNsLocalName(NAMESPACE_SOB, "RecommendationForApprovalOfAnnualReportByGeneralMeeting"),
                qnameNsLocalName(NAMESPACE_SOB, "DateOfApprovalOfAnnualReport"),
                qnameNsLocalName(NAMESPACE_SOB, "PlaceOfSignatureOfStatement"),
                qnameNsLocalName(NAMESPACE_CMN, "NameAndSurnameOfMemberOfExecutiveBoard"),
                qnameNsLocalName(NAMESPACE_CMN, "TitleOfMemberOfExecutiveBoard"),
                qnameNsLocalName(NAMESPACE_CMN, "DescriptionOfMemberOfExecutiveBoard"),
                qnameNsLocalName(NAMESPACE_SOB, "DescriptionOfObjectionsOfMemberOfExecutiveBoardOnAnnualReport"),
                qnameNsLocalName(NAMESPACE_SOB, "DescriptionOfSpecificAndAdequateGroundsForObjectionsOfMemberOfExecutiveBoardOnAnnualReport"),
                qnameNsLocalName(NAMESPACE_CMN, "NameAndSurnameOfMemberOfSupervisoryBoard"),
                qnameNsLocalName(NAMESPACE_CMN, "TitleOfMemberOfSupervisoryBoard"),
                qnameNsLocalName(NAMESPACE_CMN, "DescriptionOfMemberOfSupervisoryBoard"),
                qnameNsLocalName(NAMESPACE_SOB, "DescriptionOfObjectionsOfMemberOfSupervisoryBoardOnAnnualReport"),
                qnameNsLocalName(NAMESPACE_SOB, "DescriptionOfSpecificAndAdequateGroundsForObjectionsOfMemberOfSupervisoryBoardOnAnnualReport"),
                qnameNsLocalName(NAMESPACE_SOB, "IdentificationNumberCVRofParticipantNotPartOfTheRegisteredManagementMemberOfSupervisoryBoard"),
                qnameNsLocalName(NAMESPACE_SOB, "NameOfEntityParticipantNotPartOfTheRegisteredManagementMemberOfSupervisoryBoard"),
                qnameNsLocalName(NAMESPACE_SOB, "DescriptionOfParticipantNotPartOfTheRegisteredManagementMemberOfSupervisoryBoard"),
                qnameNsLocalName(NAMESPACE_GSD, "NameAndSurnameOfMemberOfSupervisoryCommittee"),
                qnameNsLocalName(NAMESPACE_GSD, "TitleOfMemberOfSupervisoryCommittee"),
                qnameNsLocalName(NAMESPACE_GSD, "DescriptionOfMemberOfSupervisoryCommittee"),
                qnameNsLocalName(NAMESPACE_GSD, "NameAndSurnameOfMemberOfSupervisoryCommittee"),
                qnameNsLocalName(NAMESPACE_GSD, "TitleOfMemberOfSupervisoryCommittee"),
                qnameNsLocalName(NAMESPACE_CMN, "NameAndSurnameOfLiquidator"),
                qnameNsLocalName(NAMESPACE_CMN, "TitleOfLiquidator"),
                qnameNsLocalName(NAMESPACE_CMN, "DescriptionOfLikvidator"),
                qnameNsLocalName(NAMESPACE_SOB, "DescriptionOfObjectionsOfLiquidatorOnAnnualReport"),
                qnameNsLocalName(NAMESPACE_SOB, "DescriptionOfSpecificAndAdequateGroundsForObjectionsOfLiquidatorOnAnnualReport"),
            ]),
            noncurrentAssetsQn=qnameNsLocalName(NAMESPACE_FSA, "NoncurrentAssets"),
            nameAndSurnameOfChairmanOfGeneralMeetingQn=qnameNsLocalName(NAMESPACE_GSD, "NameAndSurnameOfChairmanOfGeneralMeeting"),
            nameOfAuditFirmQn=qnameNsLocalName(NAMESPACE_CMN, "NameOfAuditFirm"),
            nameOfReportingEntityQn=qnameNsLocalName(NAMESPACE_GSD, "NameOfReportingEntity"),
            nameOfSubmittingEnterpriseQn=qnameNsLocalName(NAMESPACE_GSD, "NameOfSubmittingEnterprise"),
            otherEmployeeExpenseQn=qnameNsLocalName(NAMESPACE_FSA, "OtherEmployeeExpense"),
            otherRenderingOfReportedValueMemberQn=qnameNsLocalName(NAMESPACE_CMN, "OtherRenderingOfReportedValueMember"),
            positiveProfitThreshold=1000,
            postemploymentBenefitExpenseQn=qnameNsLocalName(NAMESPACE_FSA, "PostemploymentBenefitExpense"),
            precedingReportingPeriodEndDateQn=qnameNsLocalName(NAMESPACE_GSD, "PredingReportingPeriodEndDate"),  # Typo in taxonomy
            precedingReportingPeriodStartDateQn=qnameNsLocalName(NAMESPACE_GSD, "PrecedingReportingPeriodStartDate"),
            profitLossQn=qnameNsLocalName(NAMESPACE_FSA, "ProfitLoss"),
            proposedDividendRecognisedInEquityQn=qnameNsLocalName(NAMESPACE_FSA, "ProposedDividendRecognisedInEquity"),
            proposedExtraordinaryDividendRecognisedInLiabilitiesQn=qnameNsLocalName(NAMESPACE_FSA, "ProposedExtraordinaryDividendRecognisedInLiabilities"),
            provisionsQn=qnameNsLocalName(NAMESPACE_FSA, "Provisions"),
            registrationNumberOfTheDigitalStandardBookkeepingSystemUsedQn=qnameNsLocalName(NAMESPACE_GSD, "RegistrationNumberOfTheDigitalStandardBookkeepingSystemUsed"),
            registeredReportingPeriodDeviatingFromReportedReportingPeriodDueArbitraryDatesMemberQn=qnameNsLocalName(NAMESPACE_GSD, "RegisteredReportingPeriodDeviatingFromReportedReportingPeriodDueArbitraryDatesMember"),
            reportedValueOtherRenderingOfReportedValueDimensionQn=qnameNsLocalName(NAMESPACE_CMN, "ReportedValueOtherRenderingOfReportedValueDimension"),
            reportingClassCLargeDanish="Regnskabsklasse C, stor virksomhed",
            reportingClassCLargeEnglish="Reporting class C, large enterprise",
            reportingClassCLargeLowercaseDanish="regnskabsklasse C, stor virksomhed",
            reportingClassCLargeLowercaseEnglish="reporting class C, large enterprise",
            reportingClassCMediumDanish="Regnskabsklasse C, mellemstor virksomhed",
            reportingClassCMediumEnglish="Reporting class C, medium-size enterprise",
            reportingClassCMediumLowercaseDanish="regnskabsklasse C, mellemstor virksomhed",
            reportingClassCMediumLowercaseEnglish="reporting class C, medium-size enterprise",
            reportingClassDDanish="Regnskabsklasse D",
            reportingClassDEnglish="Reporting class D",
            reportingClassDLowercaseDanish="regnskabsklasse D",
            reportingClassDLowercaseEnglish="reporting class D",
            reportingPeriodEndDateQn=qnameNsLocalName(NAMESPACE_GSD, "ReportingPeriodEndDate"),
            reportingPeriodStartDateQn=qnameNsLocalName(NAMESPACE_GSD, "ReportingPeriodStartDate"),
            reportingResponsibilitiesOnApprovedAuditorsReportAuditQn=qnameNsLocalName(NAMESPACE_ARR, "ReportingResponsibilitiesAccordingToTheDanishExecutiveOrderOnApprovedAuditorsReportsAudit"),
            reportingResponsibilitiesOnApprovedAuditorsReportsExtendedReviewQn=qnameNsLocalName(NAMESPACE_ARR, "ReportingResponsibilitiesAccordingToTheDanishExecutiveOrderOnApprovedAuditorsReportsExtendedReview"),
            reportingObligationQns = frozenset([
                qnameNsLocalName(NAMESPACE_ARR, "ReportingResponsibilitiesAccordingToTheDanishExecutiveOrderOnApprovedAuditorsReportsEspeciallyTheCriminalCodeAndFiscalTaxAndSubsidyLegislationExtendedReview"),
                qnameNsLocalName(NAMESPACE_ARR, "ReportingResponsibilitiesAccordingToTheDanishExecutiveOrderOnApprovedAuditorsReportsEspeciallyTheCompaniesActOrEquivalentLegislationThatTheCompanyIsSubjectToExtendedReview"),
                qnameNsLocalName(NAMESPACE_ARR, "ReportingResponsibilitiesAccordingToTheDanishExecutiveOrderOnApprovedAuditorsReportsEspeciallyLegislationOnFinancialReportingInApplication"),
            ]),
            schemaRefUri="http://archprod.service.eogs.dk/taxonomy/",
            selectedElementsFromReportingClassCQn=qnameNsLocalName(NAMESPACE_FSA, "SelectedElementsFromReportingClassC"),
            selectedElementsFromReportingClassDQn=qnameNsLocalName(NAMESPACE_FSA, "SelectedElementsFromReportingClassD"),
            shorttermLiabilitiesOtherThanProvisionsQn=qnameNsLocalName(NAMESPACE_FSA, "ShorttermLiabilitiesOtherThanProvisions"),
            signatureOfAuditorsDateQn=qnameNsLocalName(NAMESPACE_ARR, "SignatureOfAuditorsDate"),
            soloMemberQn=qnameNsLocalName(NAMESPACE_CMN, "SoloMember"),
            startDateForUseOfDigitalNonregisteredBookkeepingSystemQn=qnameNsLocalName(NAMESPACE_GSD, "StartDateForUseOfDigitalNonregisteredBookkeepingSystem"),
            startDateForUseOfDigitalStandardBookkeepingSystemQn=qnameNsLocalName(NAMESPACE_GSD, "StartDateForUseOfDigitalStandardBookkeepingSystem"),
            statementOfChangesInEquityQns=frozenset([
                qnameNsLocalName(NAMESPACE_FSA, "Equity"),
                qnameNsLocalName(NAMESPACE_FSA, "IncreaseDecreaseOfEquityThroughCorrectionsOfErrors"),
                qnameNsLocalName(NAMESPACE_FSA, "IncreaseDecreaseOfEquityThroughChangesInAccountingPolicies"),
                qnameNsLocalName(NAMESPACE_FSA, "AdditionsToDisposalsOfEquityThroughMergersAndBusinessCombinations"),
                qnameNsLocalName(NAMESPACE_FSA, "IncreaseDecreaseOfEquityByDivisionAndSaleOfOtherCompany"),
                qnameNsLocalName(NAMESPACE_FSA, "IncreaseOfCapital"),
                qnameNsLocalName(NAMESPACE_FSA, "IncreaseOfCapitalByConversionOfDebt"),
                qnameNsLocalName(NAMESPACE_FSA, "DecreaseOfCapital"),
                qnameNsLocalName(NAMESPACE_FSA, "DecreaseOfCapitalDueToDeficitCoverage"),
                qnameNsLocalName(NAMESPACE_FSA, "BonusShares"),
                qnameNsLocalName(NAMESPACE_FSA, "CostRelatedToIncreaseOfCapital"),
                qnameNsLocalName(NAMESPACE_FSA, "PurchaseOfTreasuryShares"),
                qnameNsLocalName(NAMESPACE_FSA, "SalesOfTreasuryShares"),
                qnameNsLocalName(NAMESPACE_FSA, "PurchaseOfMinorityShares"),
                qnameNsLocalName(NAMESPACE_FSA, "SaleOfMinorityShares"),
                qnameNsLocalName(NAMESPACE_FSA, "Dividend"),
                qnameNsLocalName(NAMESPACE_FSA, "DividendPaid"),
                qnameNsLocalName(NAMESPACE_FSA, "DistributionsStatementOfChangesInEquity"),
                qnameNsLocalName(NAMESPACE_FSA, "ExtraordinaryDistributionsStatementOfChangesInEquity"),
                qnameNsLocalName(NAMESPACE_FSA, "IncreaseDecreaseOfInvestmentsThroughNetExchangeDifferencesEquity"),
                qnameNsLocalName(NAMESPACE_FSA, "ValueAdjustmentsOfEquity"),
                qnameNsLocalName(NAMESPACE_FSA, "AdjustmentsOfHedgingInstruments"),
                qnameNsLocalName(NAMESPACE_FSA, "OtherAdjustmentsOfEquity"),
                qnameNsLocalName(NAMESPACE_FSA, "EquityTransfersToReserves"),
                qnameNsLocalName(NAMESPACE_FSA, "ProfitLoss"),
                qnameNsLocalName(NAMESPACE_FSA, "ChangesInEquityOfTax"),
                qnameNsLocalName(NAMESPACE_FSA, "ExtraordinaryDividendPaid"),
                qnameNsLocalName(NAMESPACE_FSA, "DividendsFromTreasuryShares"),
                qnameNsLocalName(NAMESPACE_FSA, "ReceivablesShareCapitalPaid"),
                qnameNsLocalName(NAMESPACE_FSA, "Revaluations"),
                qnameNsLocalName(NAMESPACE_FSA, "DepreciationOfEquity"),
                qnameNsLocalName(NAMESPACE_FSA, "RevaluationsOfActuarialProfitLossForReportingPeriod"),
                qnameNsLocalName(NAMESPACE_FSA, "ImpairmentLossesAndDepreciationOfActuarialGainsLossesStatementOfChangesInEquity"),
                qnameNsLocalName(NAMESPACE_FSA, "DissolutionOfPreviousYearsRevaluations"),
                qnameNsLocalName(NAMESPACE_FSA, "DissolutionOfFairValueReserve"),
                qnameNsLocalName(NAMESPACE_FSA, "DissolutionOfReserves"),
                qnameNsLocalName(NAMESPACE_FSA, "AdjustmentsOfHedgingInstrumentsAtFairValue"),
                qnameNsLocalName(NAMESPACE_FSA, "AdjustmentsOfCollateralsBySaleOfInvestments"),
                qnameNsLocalName(NAMESPACE_FSA, "TransferredFromSharePremium"),
                qnameNsLocalName(NAMESPACE_FSA, "TransferToCoverageOfLosses"),
                qnameNsLocalName(NAMESPACE_FSA, "ProfitLlossFromGroupEnterprises"),
                qnameNsLocalName(NAMESPACE_FSA, "ProfitLossFromAssociates"),
                qnameNsLocalName(NAMESPACE_FSA, "ProfitLossFromParticipatingInterests"),
                qnameNsLocalName(NAMESPACE_FSA, "ReversedRevaluationsDuringReportingPeriod"),
                qnameNsLocalName(NAMESPACE_FSA, "DistributedDividendsFromGroupEnterprises"),
                qnameNsLocalName(NAMESPACE_FSA, "DistributedDividendsFromAssociates"),
                qnameNsLocalName(NAMESPACE_FSA, "DistributedDividendsFromParticipatingInterests"),
                qnameNsLocalName(NAMESPACE_FSA, "CashPaymentsConcerningFormationOfEntity"),
                qnameNsLocalName(NAMESPACE_FSA, "ContributionFromGroup"),
                qnameNsLocalName(NAMESPACE_FSA, " IncreaseDecreaseOfReservesThroughApplicationOfUnitingOfInterestsMethodEquity")
                ]),
            taxExpenseOnOrdinaryActivitiesQn=qnameNsLocalName(NAMESPACE_FSA, "TaxExpenseOnOrdinaryActivities"),
            taxExpenseQn=qnameNsLocalName(NAMESPACE_FSA, "TaxExpense"),
            typeOfAuditorAssistanceQn=qnameNsLocalName(NAMESPACE_CMN, "TypeOfAuditorAssistance"),
            typeOfBasisForModifiedOpinionOnFinancialStatementsReviewQn=qnameNsLocalName(NAMESPACE_ARR, "TypeOfBasisForModifiedOpinionOnFinancialStatementsReview"),
            typeOfDigitalNonregisteredBookkeepingSystemQn=qnameNsLocalName(NAMESPACE_GSD, "TypeOfDigitalNonregisteredBookkeepingSystem"),
            typeOfReportingPeriodDimensionQn=qnameNsLocalName(NAMESPACE_GSD, "TypeOfReportingPeriodDimension"),
            wagesAndSalariesQn=qnameNsLocalName(NAMESPACE_FSA, "WagesAndSalaries"),
        )
