locale = 'en-US'
title = 'Arelle'
enableGitInfo = true

[taxonomies]

[permalinks]
  blog = '/blog/:year/:month/:day/:slug/'

[outputs]
  home = ['HTML', 'RSS']
  page = ['HTML']
  section = ['HTML']
  taxonomy = ['HTML']
  term = ['HTML']

[[module.mounts]]
  source = 'assets'
  target = 'assets'

[[module.mounts]]
  source = 'node_modules/@fontsource-variable/instrument-sans/files/instrument-sans-latin-wght-normal.woff2'
  target = 'assets/fonts/instrument-sans-400-700.woff2'

[[module.mounts]]
  source = 'node_modules/@fontsource/dm-mono/files/dm-mono-latin-400-normal.woff2'
  target = 'assets/fonts/dm-mono-400.woff2'

[[module.mounts]]
  source = 'node_modules/@fontsource/martian-mono/files/martian-mono-latin-600-normal.woff2'
  target = 'assets/fonts/martian-mono-600.woff2'
