locale = 'en-US'
title = 'Arelle'
enableGitInfo = true

[taxonomies]

[permalinks]
  blog = '/blog/:year/:month/:day/:slug/'

[outputs]
  home = ['HTML', 'RSS']
  page = ['HTML']
  section = ['HTML']
  taxonomy = ['HTML']
  term = ['HTML']
