name: Build macOS

on:
  workflow_call:
    inputs:
      codesign_and_notarize:
        description: 'Sign and notarize code'
        required: false
        default: true
        type: boolean
      edgar_ref:
        description: 'Arelle/EDGAR branch, tag or SHA to checkout (blank for default)'
        required: false
        type: string
      python_version:
        default: '3.12'
        description: 'Python version to use'
        required: false
        type: string
      xule_ref:
        description: 'xbrlus/xule branch, tag or SHA to checkout (blank for default)'
        required: false
        type: string
    outputs:
      artifact_versioned_name:
        description: 'The file name of the DMG including the version, e.g. "arelle-macos-1.0.0.dmg".'
        value: ${{ jobs.build-macos.outputs.artifact_versioned_name }}
      uploaded_artifact_name:
        description: 'The name of the GitHub Actions artifact for the DMG.'
        value: ${{ jobs.build-macos.outputs.uploaded_artifact_name }}
  workflow_dispatch:
    inputs:
      codesign_and_notarize:
        description: 'Sign and notarize code'
        required: false
        default: true
        type: boolean
      edgar_ref:
        description: 'Arelle/EDGAR branch, tag or SHA to checkout (blank for default)'
        required: false
        type: string
      python_version:
        default: '3.12'
        description: 'Python version to use'
        required: true
        type: string
      xule_ref:
        description: 'xbrlus/xule branch, tag or SHA to checkout (blank for default)'
        required: false
        type: string

permissions: {}

jobs:
  build-macos:
    environment: release
    runs-on: macos-14
    outputs:
      artifact_versioned_name: ${{ steps.define-artifact-names.outputs.artifact_versioned_name }}
      uploaded_artifact_name: ${{ steps.define-artifact-names.outputs.uploaded_artifact_name }}

    steps:
      - name: Setup rosetta
        run: sudo softwareupdate --install-rosetta --agree-to-license
